plugins {
    id 'java'
    id 'war'
}

group 'ru.itmo.abobusik.webchik'
version '14.88 Goida Version'

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

dependencies {
    compileOnly 'jakarta.servlet:jakarta.servlet-api:5.0.0'
    compileOnly 'jakarta.servlet.jsp:jakarta.servlet.jsp-api:3.0.0'

    implementation 'jakarta.servlet.jsp.jstl:jakarta.servlet.jsp.jstl-api:2.0.0'
    implementation 'org.glassfish.web:jakarta.servlet.jsp.jstl:2.0.0'
}

war {
    archiveFileName = 'lab3.war'
}
